services:
  dev:
    volumes:
      - vscode-store:/vscode
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /lib/modules:/lib/modules:ro

  android-studio:
    volumes:
      - vscode-store:/vscode
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached

  clarinet-devnet:
    volumes:
      - vscode-store:/vscode
      - /dev:/dev
      - /lib/modules:/lib/modules
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached

  robotframework:
    volumes:
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached
      - vscode-store:/vscode

  example-application-backend:
    volumes:
      - vscode-store:/vscode

  example-application-mobile:
    volumes:
      - vscode-store:/vscode
volumes:
  vscode-store:
    external: true
    name: vscode
