name: Build and Load Branches Local Docker Images
on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
jobs:
  build-and-load-images:
    runs-on: self-hosted
    env:
      INFRA_ENV: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Maintenant, cela obtiendra tous les tags ainsi que les commits
      - name: Define VERSION
        run: |
          echo "VERSION=$(git describe --tags --abbrev=7 --match 'v*')" >> $GITHUB_ENV
      - name: Use VERSION
        run: echo "Current version is ${{ env.VERSION }}"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEV_GCLOUD_SERVICE_KEY }}
      - name: Set up Cloud SDK
        run: |
          make gcloud-config-set-project
      - name: Configure Docker for GCR
        run: |
          make gcloud-config-set-project
      - name: Configure Docker for GCR
        run: |
          make gcloud-auth-docker
      - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3
        run: |
          make docker-buildx-setup
      - name: Build and load local project images
        run: |
          make images
